Afrik={"Angola":{"Portuguese":"Olá","matin": "Bom dia", "aprem":"Boa tarde", "soir":"Boa noite"},
      "Botswana":{"English":"Hello", "Setswana":"Dumela mma"},
      "Burkina Faso":{"French":"Bonjour", "matin":"Ne y yibeogo! | I ni sogoma"},
      "Cameroon":{"French":"Bonjour", "English":"Hello"},
      "Congo":{"French":"Bonjour", "Lingala":"Mbote", "matin":"Bonjour | Mbote"},
      "Ivory Coast":{"French":"Bonjour"},
      "Egypt":{"Arabic":"As-Salaam-Alaikum", "matin":"Hello | As-Salaam-Alaikum"},
      "Ethiopia":{"Amharic":"Teanastëllën", "matin":"Hello | Teanastëllën"},
      "Gabon":{"French":"Bonjour", "matin":"Bonjour | Bole"},
      "Ghana":{"English":"Hello", "matin":"Hello | Maakyé"},
      "Kenya":{"English":"Hello", "Swahili":"Jambo", "matin":"Hello | Jambo"},
      "Lesotho":{"English":"Hello", "Sesotho":"Lumela", "matin":"Hello | Lumela"},
      "Libya":{"Arabic":"As-Salaam-Alaikum", "matin":"Hello | As-Salaam-Alaikum"},
      "Madagascar":{"French":"Bonjour", "Malagasy":"Salama", "matin":"Salama | bola tsara"},
      "Malawi":{"English":"Hello", "Chichewa":"Moni", "matin":"Hello | Moni"},
      "Mali":{"French":"Bonjour", "Bambara":"I ni ce", "matin":"Bonjour | I ni ce"},
      "Mauritania":{"Arabic":"As-Salaam-Alaikum", "Hassaniya":"Aw' walikum", "matin":"Hello | As-Salaam-Alaikum | Aw' walikum"},
      "Morroco":{"French":"Bonjour", "Arabic":"As-Salaam-Alaikum", "matin":"Bonjour | As-Salaam-Alaikum"},
      "Mozambique":{"Portuguese":"Olá", "matin":"Bom dia", "aprem":"Boa tarde", "soir":"Boa noite"},
      "Namibia":{"English":"Hello", "Afrikaans":"Hallo", "Oshiwambo":"Mwa lele po", "matin":"Hello | Hallo | Mwa lele po"},
      "Nigeria":{"English":"Hello", "Hausa":"Sànnu", "Igbo":"Ibaulachi", "Yoruba":"Bawo", "matin":"Hello | Ibaulachi | Bawo | Sànnu"},
      "Rwanda":{"English":"Hello", "French":"Bonjour", "Kinyarwanda":"Muraho", "matin":"Hello | Muraho"},
      "Senegal":{"French":"Bonjour", "Wolof":"As-Salaam-Alaikum, Nanga def?", "matin":"Bonjour | As-Salaam-Alaikum, Nanga def?"},
      "Sierra Leone":{"English":"Hello", "Krio":"Kushe", "matin":"Hello | Kushe"},
      "South Africa":{"English":"Hello", "Zulu":"Sawubona", "Xhosa":"Molo", "Afrikaans":"Hallo", "matin":"Hello | Hallo | Sawubona | Molo"},
      "Sudan":{"Arabic":"As-Salaam-Alaikum", "matin":"Hello | As-Salaam-Alaikum"},
      "Eswatini":{"English":"Hello" ,"Swati":"Sawubona", "matin":"Hello | Sawubona"},
      "Tanzania":{"English":"Hello", "Swahili":"Jambo", "matin":"Hello | Jambo"},
      "Togo":{"French":"Bonjour", "matin":"Bonjour"},
      "Tunisia":{"French":"Bonjour", "Arabic":"As-Salaam-Alaikum", "matin":"Bonjour | As-Salaam-Alaikum"},
      "Uganda":{"English":"Hello", "Luganda":"Oli otya", "Swahili":"Jambo", "matin":"Hello | Oli otya | Jambo"},
      "Zambia":{"English":"Hello", "Bemba":"Muli shani", "matin":"Hello | Muli shani"},
      "Zimbabwe":{"English":"Hello", "Shona":"Mhoro", "Ndebele":"Sawubona", "matin":"Hello | Mhoro | Sawubona"},
      "default":{"English":"Hello"}
      }
      